### ISSUE TITLE
[이슈] 백신 타입을 선택하는 GUI 제공이 필요하다

### ISSUE THREAD

**Issue by binchoo** [binchoo/selnium-kakao-vaccine-reservation#26]
## 이슈 내용
GUI에서 백신 타입을 선택할 수 없다.
현재는 "ANY" 타입을 내부적으로 사용한다. 총 4종류의 백신에 대해 예약을 시도하고 있다.

## 기대 결과
GUI에서 특정 종류의 백신을 선택할 수 있도록
- GUI 위젯이 추가됨
- 선택한 백신 종류에 대해서만 `Reservation`이 예약 요청을 보냄

**Comment by Cjwuc** [comment]
안녕하세요 관리자님.... 자꾸 질문 죄송합니다 
그 exe 파일 실행시키규 카카오 로그인까지는 되는데 좌표탐색을 누르면 cmd에 filenotfounderror: [error 2] no such file or directory: 이렇게 뜨는데 해결 방법이 있울까요?

**Comment by binchoo** [comment]
@Cjwuc 관련 에러 풀 텍스트로 볼 수 있을까요?

**Comment by Cjwuc** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "qtmain.py", line 110, in <lambda>
    capture_start = lambda: region_capture.start()
  File "service\lifecycle.py", line 27, in start
    self._handle_error(e)
  File "service\lifecycle.py", line 44, in _handle_error
    self.on_error_listener(self, error)
  File "qtmain.py", line 79, in error_handler
    raise error
  File "service\lifecycle.py", line 25, in start
    self._start()
  File "service\region.py", line 16, in _start
    self.open()
  File "service\selenium.py", line 13, in open
    self.driver = self.Driver(self.BinaryManager().install())
  File "seleniumwire\webdriver.py", line 99, in __init__
  File "seleniumwire\backend.py", line 24, in create
  File "seleniumwire\server.py", line 28, in __init__
  File "seleniumwire\utils.py", line 98, in extract_cert_and_key
  File "pkgutil.py", line 637, in get_data
  File "PyInstaller\loader\pyimod03_importers.py", line 371, in get_data
FileNotFoundError: [Errno 2] No such file or directory:

**Comment by Cjwuc** [comment]
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "threading.py", line 932, in _bootstrap_inner
> File "threading.py", line 870, in run
> File "qtmain.py", line 110, in
> capture_start = lambda: region_capture.start()
> File "service\lifecycle.py", line 27, in start
> self._handle_error(e)
> File "service\lifecycle.py", line 44, in _handle_error
> self.on_error_listener(self, error)
> File "qtmain.py", line 79, in error_handler
> raise error
> File "service\lifecycle.py", line 25, in start
> self._start()
> File "service\region.py", line 16, in _start
> self.open()
> File "service\selenium.py", line 13, in open
> self.driver = self.Driver(self.BinaryManager().install())
> File "seleniumwire\webdriver.py", line 99, in **init**
> File "seleniumwire\backend.py", line 24, in create
> File "seleniumwire\server.py", line 28, in **init**
> File "seleniumwire\utils.py", line 98, in extract_cert_and_key
> File "pkgutil.py", line 637, in get_data
> File "PyInstaller\loader\pyimod03_importers.py", line 371, in get_data
> FileNotFoundError: [Errno 2] No such file or directory:

이거 입니다 개발자니뮤ㅠ

**Comment by Cjwuc** [comment]
안녕하세요!! 개발자님 문제해결 감사합니다ㅠㅠ!!!
자꾸 질문죄송합니다!! 혹시 매크로주기 1초 설정시 계정 정지 가능성 있을까요??

**Comment by binchoo** [comment]
구현 후 1.1 릴리스에 반영하였다.

**Comment by Cjwuc** [comment]
​
​
-----Original Message-----

**Comment by binchoo** [comment]
@Cjwuc 백신 갯수 조회 및 예약할 때 사용합니다!

**Comment by Cjwuc** [comment]
​
​
-----Original Message-----
