### ISSUE TITLE
[이슈] 백신 예약 성공했을 때 'desc' 키를 응답 json에서 찾을 수 없음

### ISSUE THREAD

**Issue by binchoo** [binchoo/selnium-kakao-vaccine-reservation#36]
## 재현 절차
백신 예약에 성공한다.

## 이슈 내용
백신 예약 성공 시, 예약 스레드가 예외로 종료된다.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\wnwoq\Miniconda3\envs\vacc-qa1\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\wnwoq\Miniconda3\envs\vacc-qa1\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "qtmain.py", line 118, in <lambda>
    region=model.region, vaccine_type='ANY', run_interval=model.run_interval)
  File "F:\repositories\corona-virus-vaccine-reservation\service\lifecycle.py", line 27, in start
    self._handle_error(e)
  File "F:\repositories\corona-virus-vaccine-reservation\service\lifecycle.py", line 46, in _handle_error
    raise error
  File "F:\repositories\corona-virus-vaccine-reservation\service\lifecycle.py", line 25, in start
    self._start()
  File "F:\repositories\corona-virus-vaccine-reservation\service\reservation.py", line 41, in _start
    if self.try_reservation(organizations, try_vaccine_types):
  File "F:\repositories\corona-virus-vaccine-reservation\service\reservation.py", line 86, in try_reservation
    result_desc = response_json['desc']
KeyError: 'desc'
```

## 기대 결과
- 스레드가 정상 종료된다.
- 매크로 로그에 백신 예약 성공 문구를 출력한다.

**Comment by binchoo** [comment]
방어로직 추가하여 수정 완료.
